name: sonarr
services:
    sonarr:
        cpu_shares: 90
        command: []
        container_name: sonarr
        deploy:
            resources:
                limits:
                    memory: "16733175808"
        environment:
            PGID: "1000"
            PUID: "1000"
            TZ: America/New_York
        hostname: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        labels:
            icon: https://icon.casaos.io/main/all/sonarr.png
        network_mode: bridge
        ports:
            - target: 8989
              published: "8989"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /mnt/drive1/appdata/sonarr
              target: /config
            - type: bind
              source: /mnt/drive1
              target: /mnt/drive1
            - type: bind
              source: /mnt/drive2
              target: /mnt/drive2
            - type: bind
              source: /mnt/drive3
              target: /mnt/drive3
            - type: bind
              source: /mnt/drive4
              target: /mnt/drive4
            - type: bind
              source: /mnt/toshiba
              target: /mnt/toshiba
networks:
    default:
        name: sonarr_default
x-casaos:
    author: self
    category: self
    hostname: ""
    icon: https://icon.casaos.io/main/all/sonarr.png
    index: /
    is_uncontrolled: false
    port_map: "8989"
    scheme: http
    store_app_id: sonarr
    title:
        custom: ""
        en_us: sonarr
